language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - build-tools-29.0.2
  - android-29
  - extra-android-m2repository
  - extra-android-support
before_install:
- openssl aes-256-cbc -K $encrypted_5e787dec659c_key -iv $encrypted_5e787dec659c_iv
  -in .travis.zip.enc -out .travis.zip -d
- unzip .travis.zip
- eval "$(ssh-agent -s)"
- chmod 600 .ssh/id_rsa
- ssh-add .ssh/id_rsa
before_script:
  - chmod +x gradlew
script:
- "./gradlew assembleRelease"
addons:
  ssh_known_hosts:
  - github.com
after_script:
- git config user.name "xianfengting"
- git config user.email "xianfengting221@163.com"
- main_version_content=$(cat main-version)
- snapshot_version_content=$(cat snapshot-version)
- snapshot_version=$((10#${snapshot_version_content}))
- snapshot_version=`expr $snapshot_version + 1`
- echo -n $snapshot_version > snapshot-version
- git add snapshot-version
- git commit -s -m "Auto-update snapshot version"
- git tag -a "v${main_version_content}-sn$snapshot_version" -m "Version ${main_version_content} Snapshot $snapshot_version"
