language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - build-tools-29.0.2
  - android-29
  - extra-android-m2repository
  - extra-android-support
before_install:
- openssl aes-256-cbc -K $encrypted_5e787dec659c_key -iv $encrypted_5e787dec659c_iv
  -in .travis.zip.enc -out .travis.zip -d
- unzip .travis.zip
- eval "$(ssh-agent -s)"
- chmod 600 .ssh/id_rsa
- ssh-add .ssh/id_rsa
before_script:
  - chmod +x gradlew
script:
- "./gradlew assembleRelease"
addons:
  ssh_known_hosts:
  - github.com
after_script:
- do_deploy_content=$(cat .do-deploy)
- do_deploy=$((10#${do_deploy_content}))
- if [ $do_depoly -ne 0 ]; then
  git config user.name "xianfengting"
  git config user.email "xianfengting221@163.com"
  git checkout master
  ./gradlew generateProjectVersionFile
  project_version=$(cat project-version)
  git tag -a $project_version -m "Auto-deployed project version ${project_version}"
  fi
