language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - build-tools-29.0.2
  - android-29
  - extra-android-m2repository
  - extra-android-support
before_script:
- chmod +x gradlew
before_install:
- openssl aes-256-cbc -K $encrypted_5e787dec659c_key -iv $encrypted_5e787dec659c_iv
  -in keystore.jks.enc -out keystore.jks -d
- openssl aes-256-cbc -K $encrypted_5e787dec659c_key -iv $encrypted_5e787dec659c_iv
  -in id_rsa.enc -out .ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 .ssh/id_rsa
- ssh-add .ssh/id_rsa
script:
- "./gradlew assembleRelease"
